### ISSUE TITLE
This is not an issue. I just want to explain how to use this library on Android

### ISSUE THREAD

**Issue by RahimRahimov** [sargue/mailgun#12]
Add this lines to gradle dependencies and configurations modules.
That is it. So after this steps you can use this library on android.

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'net.sargue:mailgun:1.3.2'
}
configurations {
    compile.exclude group: 'javax.inject', module: 'javax.inject'
}

**Comment by sargue** [comment]
Seems that you are pinning jersey to version 2.18, is that all that you need to do to use it?

**Comment by sargue** [comment]
That was discussed in issue #1 . Closing this and updating main README. Thanks for reporting.
