### ISSUE TITLE
adding header

### ISSUE THREAD

**Issue by phenom1711** [sargue/mailgun#17]
hello,

can i add header on email? if yes, how to add?

thankyou

**Comment by sargue** [comment]
Yes, you can add custom headers to the outgoing email. Just use the `parameter(String,String)` method of the `MailBuilder` class and send a parameter starting with ' h:'  as [explained in the mailgun documentation](https://documentation.mailgun.com/api-sending.html#sending).

```java
MailBuilder.using(configuration)
            .to("marty@mcfly.com")
            .subject("This is a plain text test")
            .text("Hello world!")
            .parameter("h:CustomHeader", "The header value")
            .build()
            .send();
```

The above example will add a header named *CustomHeader* to the message.
