### ISSUE TITLE
Having slight issue with sending attachments when emailing

### ISSUE THREAD

**Issue by StrawberryJS** [sargue/mailgun#18]
I appreciate this is more than likely something I am doing as aposed to a bug with your system. 

I am having difficulty sending emails with attachments. I am successfully sending the email but the attachment does not come thorugh.

```java
MailBuilder builder = new MailBuilder(this.configuration);
            builder.from((!from.isEmpty() ? from : Settings.Retrieve("MAILGUN_FROM_NAME") + " <" + Settings.Retrieve("MAILGUN_FROM_ADDRESS") + ">"));
            builder.to(to);
            if(!cc.isEmpty()) {
                builder.cc(cc);
            }
            if(!bcc.isEmpty()) {
                builder.bcc(bcc);
            }
            builder.subject(subject);
            builder.html(html);
            if (!files.isEmpty()) {
                String[] attachedFiles = files.split(",");
                for (String file: attachedFiles) {
                    URL url = new URL(file);
                    String tDir = System.getProperty("java.io.tmpdir");
                    String path = tDir + "tmp" + ".txt";
                    File newFile = new File(path);
                    FileUtils.copyURLToFile(url, newFile);
                    builder.multipart().attachment(newFile);
                    newFile.deleteOnExit();
                }
            }
            builder.build().send();
```

Here is an example of my code. I am moderately new to Java so may have done something completely incorrect. The attachment is an external URL.

I receive no errors when debugging.

Any help would be greatly appreciated.

Thanks,
Jamie

**Comment by sargue** [comment]
The `MailBuilder.multipart()` returns a new kind of object: a `MultipartBuilder`. You are ignoring the return of that object so you keep working on the original one.

Change the final part of your code with this:

    if (!files.isEmpty()) {
        MultipartBuilder multipartBuilder = builder.multipart();
        String[] attachedFiles = files.split(",");
        for (String file: attachedFiles) {
            URL url = new URL(file);
            String tDir = System.getProperty("java.io.tmpdir");
            String path = tDir + "tmp" + ".txt";
            File newFile = new File(path);
            FileUtils.copyURLToFile(url, newFile);
            multipartBuilder.attachment(newFile);
            newFile.deleteOnExit();
        }
        multipartBuilder.build().send();
    } else {
        builder.build().send();
    }

It should work.

The full example would be more correct like this:

    MailBuilder builder = new MailBuilder(this.configuration)
        .from((!from.isEmpty() ? from : Settings.Retrieve("MAILGUN_FROM_NAME") + " <" + Settings.Retrieve("MAILGUN_FROM_ADDRESS") + ">"))
        .to(to);
    if(!cc.isEmpty()) {
        builder = builder.cc(cc);
    }
    if(!bcc.isEmpty()) {
        builder = builder.bcc(bcc);
    }
    builder = builder.subject(subject)
                     .html(html);
    if (!files.isEmpty()) {
        MultipartBuilder multipartBuilder = builder.multipart();
        String[] attachedFiles = files.split(",");
        for (String file: attachedFiles) {
            URL url = new URL(file);
            String tDir = System.getProperty("java.io.tmpdir");
            String path = tDir + "tmp" + ".txt";
            File newFile = new File(path);
            FileUtils.copyURLToFile(url, newFile);
            multipartBuilder.attachment(newFile);
            newFile.deleteOnExit();
        }
        multipartBuilder.build().send();
    } else {
        builder.build().send();
    }

The builder (or fluent API) pattern is supposed to be used chaining calls.

Anyway I acknowledge that the API design is far from being the best possible. It was my first public API so I'm facing the inability to change it without bumping to version 2. The next version would be hopefully easier.

Thanks for using the library. Salut!

**Comment by StrawberryJS** [comment]
Perfect, it does indeed work now. 

Thank you for taking the time to help me with this.

**Comment by sargue** [comment]
You're welcome. I'm glad it's useful for you now.
