### ISSUE TITLE
1.1.0 not available

### ISSUE THREAD

**Issue by pcj** [sargue/mailgun#2]
Was looking to try this out but the 1.1.0 is not available via standard maven repositories:

```
<dependency>
    <groupId>net.sargue</groupId>
    <artifactId>mailgun</artifactId>
    <version>1.1.0</version>
</dependency>
```

`1.0.0` is, but it seems like a lot changed between these two versions.

**Comment by sargue** [comment]
I know! Sorry, I'm trying to publish now through Bintray's jcenter instead of Sonatype's Maven Central and it's taking longer than expected. Thanks for reporting.

**Comment by sargue** [comment]
Oh, by the way, the package is already published on my bintray's repository. You can use that temporarily.

https://bintray.com/sargue/maven/mailgun/view

**Comment by sargue** [comment]
It's finally available on Maven Central. Sorry for the delay.
