### ISSUE TITLE
iCal Mime Messages

### ISSUE THREAD

**Issue by pgali** [sargue/mailgun#25]
Can you please provide an example of attaching iCal messages?
This C# based example show how to send iCal messages via maligun, but there are no java equivalent.
https://stackoverflow.com/questions/38840101/how-to-send-a-ical-invite-with-mailgun-rest-api-c

**Comment by sargue** [comment]
It seems, from the answer to the SO question, that you need the MIME endpoint which this library doesn't yet support. See #22 .

Once that support is implemented it shouldn't be too complicated.
