### ISSUE TITLE
Issue below API 19

### ISSUE THREAD

**Issue by baignomi** [sargue/mailgun#26]
Caused by: java.lang.NoClassDefFoundError: java.util.Objects

this error occur.
Please help!

**Comment by sargue** [comment]
I am assuming that by "Issue below API 19" you mean that you have problems running on Android below that API level.

The error reported is about the lack of a class: `java.util.Objects`. That class is available from Java 7. This library won't work on anything less so I suppose the Android version you are targeting is below that Java version or simply lacks the class.

**Comment by baignomi** [comment]
Yes I want to run it on API Level 18.
is there a way that I can run it on Below 19 using this Lib?

**Comment by sargue** [comment]
No.

![image](https://user-images.githubusercontent.com/333808/34554985-c71647bc-f12f-11e7-92f9-f14cbe4d8467.png)
