### ISSUE TITLE
Unable to pass the HTTPHeader

### ISSUE THREAD

**Issue by chapcoder** [sargue/mailgun#30]
I have used the Mailgun api ,net.sargue.mailgun
there is only provision of setting the APIKEY
Configuration configuration = new Configuration()
			    .domain("https://sgout-dv.allstate.com/sg/b2b/SMCE/AgencyEmail/SGE/")
			    .apiKey("bce4e20axxxxxxxxxxx27-b6183ad4-ae0c0de6");
I supposed to pass the "Authorization" Header along with above APIkey, but configuration is only limited to pass apikey.
Is there any way to pass the Headers.

**Comment by sargue** [comment]
Hello. I think you've got it wrong. I will try to point out some issues that I can see:

- the domain is your mailgun configured domain, like `mg.example.com`
- your api key is meant to be **secret**, don't publish it on the internet
- you don't need to pass the authorization header, that's handled by the library, just put the [configuration values](https://github.com/sargue/mailgun#configuration)

**Comment by chapcoder** [comment]
Thanks for your reply.
Just passing apikey didn't work, there is one more security layer which we
have to pass through for that we must send the authorisation header. When I
used normal rest template call where it has provision of passing headers it
had worked fine. Now I want to use your library and achieve this.
Suggest me is there any way I can send authorized header.

Regards,
Ranjan

**Comment by sargue** [comment]
Hi Ranjan,

I'm sorry to tell you that the library doesn't allow you to change the HTTP headers sent to mailgun.

I am working on version 2 of the library which will allow more extension options but there is no schedule right now.
