### ISSUE TITLE
How to send HTML with thymeleaf

### ISSUE THREAD

**Issue by kopax** [sargue/mailgun#35]
Hi @Sargue, 

I am importing a `String` that is an HTML builded with thymeleaf, I'd like to send the email with HTML content, but not sure how I can do, I have tried to use `Body.builder().p(myHtml)`, also tried `.text(myHtml)`, I always end up with text.

How can I send the html myself?

**Comment by sargue** [comment]
You closed the issue, I guess you found the `html()` method. :-)

**Comment by kopax** [comment]
Instead, I did, thank you
