### ISSUE TITLE
inline attachments

### ISSUE THREAD

**Issue by lancedfr** [sargue/mailgun#4]
I dont know if inline attachments is supported.
This would be a great feature to add?
Please see link below on inline attachments
https://documentation.mailgun.com/user_manual.html#inline-image

**Comment by lancedfr** [comment]
Thought I'd attach an image from one of my integration tests of the inline attachment, works great ;)

![untitled](https://cloud.githubusercontent.com/assets/2567632/17118237/1d7bc5b0-52c0-11e6-9079-76bdbe4e47c7.png)

**Comment by sargue** [comment]
Merged PR. Thanks for the contribution.
