### ISSUE TITLE
Please add information for using the EU API in the documentation

### ISSUE THREAD

**Issue by aqua-pro** [sargue/mailgun#40]
Dear creator,

I really appreciate your library, I use it in my projects since long ago

I've been wondering why I wasn't able to send mails, until I finally solved it

Please add a warning or example in configuration for EU mailgun API, as I'm sure I won't be the last one to find this issue. This can be a rather invisible issue, making you wonder what's wrong for a long time

`.apiUrl("https://api.eu.mailgun.net/v3")`

Thank you
Best regards

**Comment by sargue** [comment]
Indeed, thanks for the tip.
