### ISSUE TITLE
Validate that template exists before sending

### ISSUE THREAD

**Issue by DSKostadinov** [sargue/mailgun#41]
Currently if you provide a name of a template that does not exist in mailgun it returns a success response, however the message is never sent as the template does not exist. This can be implemented using the GET /domain/templates endpoint which returns a list of the templates that exist for your domain.

**Comment by sargue** [comment]
Ok, so what's your proposal? Should the library check for the existence of the template before sending the message?

**Comment by DSKostadinov** [comment]
Call GET v3/domain/templates if the user has set a template with MailBuilder.template("templateName)" and check whether the returned list contains "templateName". If it does not - return an error message to the user.

**Comment by sargue** [comment]
That will generate a new API call potentially each time a message is sent through the library, even if the template is correct. The library code will be more complex with this check (how to do the call, sync/async?, wait for the answer, etc), and it will incur in a serious performance penalty (twice the API calls).

**Comment by DSKostadinov** [comment]
That is correct, maybe it can be left up to the user to make sure the template name exists. I can implement it on my end if we really require it. You can close the issue, thanks.

**Comment by sargue** [comment]
Indeed, it makes more sense to left this to the library user. It seems you are implementing a product that uses the library, then I agree you can check this when the user sets the template name.
