### ISSUE TITLE
Support for JavaEE to Jakarta package naming migration

### ISSUE THREAD

**Issue by islom-kh** [sargue/mailgun#46]
when i upgrade project to spring boot 3, there is an error which realated with mailgun configuration, 
Caused by: java.lang.ClassNotFoundException: javax.ws.rs.core.MultivaluedMap
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 56 common frames omitted
	
Spring boot 3 change javax. to jakarta. package, does anyone have a solution ?

**Comment by sargue** [comment]
I don't have any solution right now. I will give this a look when I have some time.

**Comment by Smart7077** [comment]
thanks

**Comment by sargue** [comment]
I've deployed a snapshot version that you can try. It should be compatible with Jakarta EE 9 and requires Java 8. The version is 2.0.0-SNAPSHOT and it's only published on the snapshot repository.

You will need to add the Sonatype snapshot repository.

Could you please give it a try and let me know if it's working for you?

**Comment by islom-kh** [comment]
ok. thanks

**Comment by sargue** [comment]
Has anyone tested this?

**Comment by hendisantika** [comment]
> I've deployed a snapshot version that you can try. It should be compatible with Jakarta EE 9 and requires Java 8. The version is 2.0.0-SNAPSHOT and it's only published on the snapshot repository.
> 
> You will need to add the Sonatype snapshot repository.
> 
> Could you please give it a try and let me know if it's working for you?

Where I can find the newest version?

**Comment by pkubowicz** [comment]
I'm using 2.0.0-SNAPSHOT and found no problems.

Can you release the stable 2.0.0 please? Snapshot versions reduce performance of Gradle builds.

**Comment by sargue** [comment]
> I'm using 2.0.0-SNAPSHOT and found no problems.
> 
> Can you release the stable 2.0.0 please? Snapshot versions reduce performance of Gradle builds.

Thanks for testing it. I agree, I will publish 2.0.0 ASAP.

**Comment by sargue** [comment]
Done.

It should show up in the following hours. If not, please let me know.

**Comment by hendisantika** [comment]
> Done.
> 
> It should show up in the following hours. If not, please let me know.

Is it already on maven central?
