### ISSUE TITLE
Response to return message body

### ISSUE THREAD

**Issue by galatent** [sargue/mailgun#7]
The Response object has properties for the responseType and responseCode, but does not handle the message body, which is returned in JSON format from POST requests.
e.g:
On successfully submitting a message (i.e. responseCode 200), the following response message is returned:

`{
  "id": "<20160902095021.16212.7900.87F2C8F1@mydomain.com>",
  "message": "Queued. Thank you."
}`

This is useful as it returns the message id. Retrieving this is necessary as I wish to store email events and use webhooks to update the email state.

Revised version of Response.java:
`
package net.sargue.mailgun;

/**
 * Represents a response from the Mailgun service.
 */
public class Response {
    public enum ResponseType {
        OK, BAD_REQUEST, UNAUTHORIZED, REQUEST_FAILED, NOT_FOUND, SERVER_ERROR
    }

    private ResponseType responseType;
    private int responseCode;
    private String responseMessage;

    Response(javax.ws.rs.core.Response response) {
        responseCode = response.getStatus();
        responseMessage = response.readEntity(String.class);
        switch (responseCode) {
            case 200:
                responseType = ResponseType.OK;
                break;
            case 400:
                responseType = ResponseType.BAD_REQUEST;
                break;
            case 401:
                responseType = ResponseType.UNAUTHORIZED;
                break;
            case 402:
                responseType = ResponseType.REQUEST_FAILED;
                break;
            case 404:
                responseType = ResponseType.NOT_FOUND;
                break;
            default:
                responseType = ResponseType.SERVER_ERROR;
        }
    }

    /**
     * The type of the response.
     *
     * @return the type of the response
     */
    public ResponseType responseType() {
        return responseType;
    }

    /**
     * The HTTP status code of the response.
     *
     * The different recognized codes are better encoded with the
     * {@link ResponseType}. This method accesses the exact status code.
     *
     * @return the HTTP status code of the response
     */
    public int responseCode() {
        return responseCode;
    }
    
    /**
     * The HTTP message body of the response.
     *
     * @return the HTTP message body of the response
     */
    public String responseMessage() {
        return responseMessage;
    }

    /**
     * Shortcut method for checking if the response is ok. Equivalent of
     * checking if the {@link ResponseType} is {@code ResponseType.OK}.
     *
     * @return if the request was a success
     */
    public boolean isOk() {
        return responseType == ResponseType.OK;
    }
}
`

**Comment by sargue** [comment]
Nice addition, thanks for reporting. I will take a look at it ASAP, seems easy and a very reasonable funcionality.
